# 2.2 Метод Гаусса с выбором главного элемента по строке

In [6]:
import numpy as np
import typing as tp
import scipy.linalg as linalg
import scipy.stats as sps

from comp_pkg import LU_Solver

### 1 пример

In [3]:
def print_result(A, b):
    solver = LU_Solver(A, b)

    L, U, Q, solution = solver.solve()

    print(f"L - {L}")
    print(f"U - {U}")
    print(f"Q - {Q}")

    print(f"Ошибка вычисления - {np.linalg.norm(A @ solution - b):.10f}")


In [4]:
A = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 9]
])

b = np.array([1, 2, 3])

print_result(A, b)

L - [[1.         0.         0.        ]
 [1.66666667 1.         0.        ]
 [3.         2.25       1.        ]]
U - [[ 3.          1.          2.        ]
 [ 0.          1.33333333  0.66666667]
 [ 0.          0.         -0.5       ]]
Q - [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Ошибка вычисления - 0.0000000000


### 2 пример - матрица гильберта

In [5]:
A = linalg.hilbert(5)


b = np.array([1, 2, 3, 4, 5])

print_result(A, b)

L - [[1.         0.         0.         0.         0.        ]
 [0.5        1.         0.         0.         0.        ]
 [0.33333333 1.06666667 1.         0.         0.        ]
 [0.25       1.         1.5        1.         0.        ]
 [0.2        0.91428571 1.71428571 2.03174603 1.        ]]
U - [[ 1.00000000e+00  3.33333333e-01  5.00000000e-01  2.00000000e-01
   2.50000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  6.66666667e-02
   7.50000000e-02]
 [ 0.00000000e+00  1.38777878e-17 -5.55555556e-03  5.07936508e-03
   3.33333333e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  7.14285714e-04
   3.57142857e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.16840434e-19
  -1.13378685e-05]]
Q - [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
Ошибка вычисления - 0.0000000000


### Пример 3, матрица гильберта размер 10

In [22]:
A = linalg.hilbert(15)

b = sps.norm.rvs(size=15, loc=2, scale=0.5)

print_result(A, b)

L - [[1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.00000000e-01 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.33333333e-01 1.06666667e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.50000000e-01 1.00000000e+00 1.70454545e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.00000000e-01 9.14285714e-01 2.14285714e+00 2.09523810e+0

### Пример 4, большая матрица гильберта

In [19]:
A = linalg.hilbert(100)

b = sps.norm.rvs(size=100, loc=2, scale=0.5)

print_result(A, b)

L - [[1.         0.         0.         ... 0.         0.         0.        ]
 [0.5        1.         0.         ... 0.         0.         0.        ]
 [0.33333333 1.06666667 1.         ... 0.         0.         0.        ]
 ...
 [0.01020408 0.07918367 0.6787172  ... 1.         0.         0.        ]
 [0.01010101 0.07840784 0.67266161 ... 1.5407475  1.         0.        ]
 [0.01       0.07764706 0.66671248 ... 1.66001149 0.00235183 1.        ]]
U - [[ 1.00000000e+00  3.33333333e-01  1.25000000e-01 ...  1.04166667e-02
   1.28205128e-02  1.31578947e-02]
 [ 0.00000000e+00  8.33333333e-02  4.86111111e-02 ...  5.10094502e-03
   6.24797144e-03  6.40806562e-03]
 [ 0.00000000e+00  1.38777878e-17  6.48148148e-03 ...  1.29085139e-03
   1.56199286e-03  1.59927792e-03]
 ...
 [ 0.00000000e+00 -8.67361738e-19  0.00000000e+00 ... -2.96826653e-18
  -1.79327198e-18 -1.36119880e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   4.85957833e-18 -4.15726209e-19]
 [ 0.00000000e+00 

In [17]:
print(np.linalg.solve(A, b))

[ 1.76221666e+10 -2.77441587e+12  1.09584503e+14 -1.88618823e+15
  1.74229574e+16 -9.47233983e+16  3.09990920e+17 -5.67721597e+17
  3.29717599e+17  8.78591234e+17 -2.23941399e+18  2.15135414e+18
 -6.53215714e+17 -3.63449543e+17 -3.53519626e+17  1.32636782e+18
 -2.59526509e+17 -5.26228644e+17 -1.26412870e+18  1.64138808e+18
 -6.90767263e+17  1.49235620e+18 -1.13285858e+18 -1.03065887e+18
  1.09871159e+18  1.71558503e+18 -8.32678142e+17 -2.07662511e+18
  5.92079946e+17 -1.01696074e+18 -3.15423647e+17  3.06880168e+18
 -1.34872865e+18  1.48644919e+18 -1.61563580e+18  1.82345645e+18
 -1.53359412e+17 -1.29195992e+18  2.86844194e+17 -4.74947448e+17
 -1.73566241e+17 -1.24451812e+18  4.63550573e+17 -2.33699244e+17
  1.30852986e+18 -5.47004427e+17 -1.24710489e+18  1.49868325e+18
  7.58370519e+17  4.85709364e+17 -2.89114142e+17  7.28672964e+17
  3.24709109e+18 -5.13188433e+18 -1.38273971e+18  1.49741054e+18
  3.93847772e+17  1.41342653e+18 -1.08557972e+18 -5.48681432e+16
 -1.13294339e+18 -1.02350

In [18]:
print(LU_Solver(A, b).solve()[-1])

[-5.19165989e+09  8.08428553e+11 -3.00254236e+13  4.52391732e+14
 -3.22790768e+15  9.84473495e+15  5.84787847e+15 -1.34256990e+17
  3.86967598e+17 -3.91112617e+17 -1.78662690e+17  6.03691063e+17
 -3.17176225e+17  5.13253348e+17 -8.26287877e+17 -1.05902867e+18
  2.35895948e+18  2.58425474e+16 -7.32418733e+17 -1.14359173e+18
  6.59415025e+16  9.92580870e+17 -9.72986484e+17  1.06336709e+18
  1.83478709e+18 -8.20927749e+17 -8.35095426e+17 -2.44925736e+18
 -1.04023512e+18  1.15932530e+18  4.06107267e+18 -6.83859049e+17
 -1.93467612e+17 -4.26181604e+17 -1.09561999e+16 -1.92244686e+18
 -4.35500878e+17  1.39886790e+18 -1.98344273e+18  4.08891616e+18
 -1.34965680e+18 -1.41908728e+17 -7.43331245e+17  1.88627567e+17
 -2.72189431e+18  2.12426399e+18  2.13304001e+18 -1.97288165e+18
  4.84675496e+17  1.31746764e+18 -6.74096004e+17  1.83172845e+17
  4.74661685e+17 -1.50404434e+18  1.22669757e+18 -2.74850168e+18
  1.13817090e+18  1.46129930e+18 -1.23346624e+18 -1.97388834e+18
 -9.20974955e+17  2.02681