# 2.2 Метод Гаусса с выбором главного элемента по строке

In [9]:
import numpy as np
import typing as tp
import scipy.linalg as linalg

from comp_pkg import LU_Solver

### 1 пример

In [5]:
def print_result(A, b):
    solver = LU_Solver(A, b)

    L, U, Q, solution = solver.solve()

    print(f"L - {L}")
    print(f"U - {U}")
    print(f"Q - {Q}")

    print(f"Ошибка вычисления - {np.linalg.norm(A @ solution - b):.10f}")


In [6]:
A = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 9]
])

b = np.array([1, 2, 3])

print_result(A, b)

L - [[1.         0.         0.        ]
 [1.66666667 1.         0.        ]
 [3.         2.25       1.        ]]
U - [[ 3.          1.          2.        ]
 [ 0.          1.33333333  0.66666667]
 [ 0.          0.         -0.5       ]]
Q - [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Ошибка вычисления - 0.0000000000


### 2 пример - матрица гильберта

In [11]:
A = linalg.hilbert(5)


b = np.array([1, 2, 3, 4, 5])

print_result(A, b)

L - [[1.         0.         0.         0.         0.        ]
 [0.5        1.         0.         0.         0.        ]
 [0.33333333 1.06666667 1.         0.         0.        ]
 [0.25       1.         1.5        1.         0.        ]
 [0.2        0.91428571 1.71428571 2.03174603 1.        ]]
U - [[ 1.00000000e+00  3.33333333e-01  5.00000000e-01  2.00000000e-01
   2.50000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  6.66666667e-02
   7.50000000e-02]
 [ 0.00000000e+00  1.38777878e-17 -5.55555556e-03  5.07936508e-03
   3.33333333e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  7.14285714e-04
   3.57142857e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.16840434e-19
  -1.13378685e-05]]
Q - [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
Ошибка вычисления - 0.0000000000
